export const USERS_SERVICE = 'USERS_SERVICE';
export const NOTIFICATIONS_SERVICE = 'NOTIFICATIONS_SERVICE';
export const CONTENT_SERVICE = 'CONTENT_SERVICE';
export const EVENTS_SERVICE = 'EVENTS_SERVICE';
